version: "3"
services:
  db: 
    container_name: db
    image: redis
    expose: 
      - "6379"
  backend:
    container_name: backend
    depends_on: 
      - db
    build: ./backend
    command: go run main.go
    environment:
      - REDIS_DNS=db
    expose:
      - "9000"
  frontend:
    container_name: frontend
    depends_on: 
      - backend
    build: ./frontend
    command: go run main.go
    ports:
      - "8080:8080"
    environment:
      - BACKEND_DNS=backend